- name: VARS
  set_fact:
    promtail_config_dir: "/etc/loki/"

- name: Delete old config files
  file:
    path: "{{ promtail_config_dir }}promtail-config.yaml"
    state: absent

# - name: Downlload promtail
#   shell: dnf install promtail -y
#   run_once: true

- name: create DIRECTORIES
  shell: mkdir -p {{item}} 
  loop:
    - "{{ promtail_config_dir }}"

- name: COPY TEMPLATE CONFIG
  template: 
    src: "{{item}}.j2"
    dest: "{{ promtail_config_dir }}{{item}}"
    mode: 0644
  loop: 
    - "promtail-config.yaml"

- name: Install systemd service file
  copy:
    dest: /etc/systemd/system/promtail.service
    content: |
      [Unit]
      Description=Promtail service
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/promtail -config.file={{ promtail_config_dir }}promtail-config.yaml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Ensure Promtail is enabled and running
  systemd:
    name: promtail
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart Promtail service
  systemd:
    name: promtail
    state: restarted
    enabled: yes