apiVersion: 1
datasources:
  - name: Loki # Отображаемое имя нашего источника данных
    type: loki # Тип источника
    access: proxy 
    orgId: 1 # (единица адм. деления в Grafana) которой будет доступен источник (хуйня для графаны)
    url: http://loki:3100 # Адрес откуда получать данные (здесь мы используем имя сервиса loki)
    basicAuth: false # Отключение авторизации для локи блять
    isDefault: true 
    version: 1 
    editable: false # для отсутствие редактирования